// Sends a real invitation email and records the invite.
// Requires (Vercel env vars): SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, APP_URL
import { createClient } from "@supabase/supabase-js";

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });
  const { orgId, email, role, accessToken } = req.body || {};
  if (!orgId || !email || !accessToken) return res.status(400).json({ error: "Missing details." });

  const url = process.env.SUPABASE_URL, service = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !service) return res.status(500).json({ error: "Server is not configured for invites yet." });

  const admin = createClient(url, service, { auth: { persistSession: false } });

  // 1. Confirm the caller is signed in and may manage this org's team.
  const { data: userInfo, error: authErr } = await admin.auth.getUser(accessToken);
  if (authErr || !userInfo?.user) return res.status(401).json({ error: "Not signed in." });
  const { data: mem } = await admin.from("memberships").select("role,permissions,status")
    .eq("org_id", orgId).eq("user_id", userInfo.user.id).maybeSingle();
  const allowed = mem && mem.status === "active" &&
    (["owner","admin"].includes(mem.role) || (mem.permissions||[]).includes("team.manage"));
  if (!allowed) return res.status(403).json({ error: "You don't have permission to invite people." });

  // 2. Enforce the seat limit.
  const { data: org } = await admin.from("organizations").select("name,seats,status").eq("id", orgId).single();
  if (!org) return res.status(404).json({ error: "Studio not found." });
  if (org.status === "suspended" || org.status === "cancelled") return res.status(402).json({ error: "This subscription is not active." });
  const { count: used } = await admin.from("memberships").select("id",{count:"exact",head:true}).eq("org_id", orgId);
  const { count: pending } = await admin.from("invites").select("id",{count:"exact",head:true}).eq("org_id", orgId).is("accepted_at", null);
  if ((used||0) + (pending||0) >= (org.seats||0)) return res.status(402).json({ error: "No seats left — add more in Settings." });

  // 3. Record the invite (token generated by the database).
  await admin.from("invites").delete().eq("org_id", orgId).eq("email", email).is("accepted_at", null);
  const { data: invite, error: invErr } = await admin.from("invites")
    .insert({ org_id: orgId, email, role: role || "member", invited_by: userInfo.user.id })
    .select().single();
  if (invErr) return res.status(500).json({ error: invErr.message });

  // 4. Email it. Supabase sends the message; the link carries our invite token.
  const appUrl = process.env.APP_URL || `https://${req.headers.host}`;
  const redirectTo = `${appUrl}/?invite=${invite.token}`;
  const { error: mailErr } = await admin.auth.admin.inviteUserByEmail(email, { redirectTo });
  if (mailErr && !/already registered/i.test(mailErr.message)) {
    // Existing users can't be "invited" again — send them a magic link instead.
    const { error: linkErr } = await admin.auth.admin.generateLink({ type: "magiclink", email, options: { redirectTo } });
    if (linkErr) return res.status(200).json({ ok: true, emailed: false, link: redirectTo, note: "Invite recorded, but the email could not be sent. Share the link manually." });
  }
  return res.status(200).json({ ok: true, emailed: true });
}
