// Records a team invite and emails it.
// Preferred email path: Resend (set RESEND_API_KEY + INVITE_FROM, e.g. "Huddle <invites@yourdomain.com>").
// Falls back to Supabase's built-in invite email if Resend isn't configured.
// Always returns the shareable link so the inviter can copy it if email fails.
// Requires: SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, APP_URL
import { createClient } from "@supabase/supabase-js";

async function sendViaResend({ to, link, orgName, fromDefault }) {
  const key = process.env.RESEND_API_KEY;
  if (!key) return { sent: false, reason: "no-resend" };
  const from = process.env.INVITE_FROM || fromDefault;
  const html = `
    <div style="font-family:system-ui,-apple-system,sans-serif;max-width:520px;margin:auto">
      <h2 style="color:#1f2d4e">You're invited to ${orgName || "a studio"} on Huddle</h2>
      <p>You've been invited to join the team. Click below to set up your account with this email address.</p>
      <p style="margin:24px 0">
        <a href="${link}" style="background:#1f2d4e;color:#fff;text-decoration:none;padding:12px 20px;border-radius:8px;font-weight:600">Accept invitation</a>
      </p>
      <p style="color:#64748b;font-size:13px">Or paste this link into your browser:<br>${link}</p>
    </div>`;
  try {
    const r = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
      body: JSON.stringify({ from, to: [to], subject: `You're invited to ${orgName || "join a team"} on Huddle`, html }),
    });
    if (r.ok) return { sent: true };
    const b = await r.json().catch(() => ({}));
    return { sent: false, reason: b.message || `resend ${r.status}` };
  } catch (e) { return { sent: false, reason: e.message }; }
}

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });
  const { orgId, email, role, accessToken } = req.body || {};
  if (!orgId || !email || !accessToken) return res.status(400).json({ error: "Missing details." });

  const url = process.env.SUPABASE_URL, service = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !service) return res.status(500).json({ error: "Server is not configured for invites yet." });
  const admin = createClient(url, service, { auth: { persistSession: false } });

  const { data: userInfo, error: authErr } = await admin.auth.getUser(accessToken);
  if (authErr || !userInfo?.user) return res.status(401).json({ error: "Not signed in." });
  const { data: mem } = await admin.from("memberships").select("role,permissions,status")
    .eq("org_id", orgId).eq("user_id", userInfo.user.id).maybeSingle();
  const allowed = mem && mem.status === "active" &&
    (["owner", "admin"].includes(mem.role) || (mem.permissions || []).includes("team.manage"));
  if (!allowed) return res.status(403).json({ error: "You don't have permission to invite people." });

  const { data: org } = await admin.from("organizations").select("name,seats,status").eq("id", orgId).single();
  if (!org) return res.status(404).json({ error: "Studio not found." });

  // Free internal domains skip subscription/seat limits.
  const FREE_DOMAINS = (process.env.FREE_DOMAINS || "thealloy.com").split(",").map(d => d.trim().toLowerCase()).filter(Boolean);
  const inviterDomain = (userInfo.user.email || "").split("@")[1]?.toLowerCase();
  const isFreeOrg = inviterDomain && FREE_DOMAINS.includes(inviterDomain);

  if (!isFreeOrg) {
    if (org.status === "suspended" || org.status === "cancelled") return res.status(402).json({ error: "This subscription is not active." });
    const { count: used } = await admin.from("memberships").select("id", { count: "exact", head: true }).eq("org_id", orgId);
    const { count: pending } = await admin.from("invites").select("id", { count: "exact", head: true }).eq("org_id", orgId).is("accepted_at", null);
    if ((used || 0) + (pending || 0) >= (org.seats || 0)) return res.status(402).json({ error: "No seats left — add more in Settings." });
  }

  // Record the invite (token generated by the database).
  await admin.from("invites").delete().eq("org_id", orgId).eq("email", email).is("accepted_at", null);
  const { data: invite, error: invErr } = await admin.from("invites")
    .insert({ org_id: orgId, email, role: role || "member", invited_by: userInfo.user.id })
    .select().single();
  if (invErr) return res.status(500).json({ error: invErr.message });

  const appUrl = process.env.APP_URL || `https://${req.headers.host}`;
  const link = `${appUrl}/?invite=${invite.token}`;
  const host = (() => { try { return new URL(appUrl).hostname; } catch (_) { return "huddle.app"; } })();

  // 1) Preferred: Resend (reliable, not rate-limited, branded).
  const resend = await sendViaResend({ to: email, link, orgName: org.name, fromDefault: `Huddle <onboarding@${host}>` });
  if (resend.sent) return res.status(200).json({ ok: true, emailed: true, via: "resend", link });

  // 2) Fallback: Supabase built-in invite email (rate-limited to a couple/hour).
  try {
    const { error: mailErr } = await admin.auth.admin.inviteUserByEmail(email, { redirectTo: link });
    if (!mailErr) return res.status(200).json({ ok: true, emailed: true, via: "supabase", link });
    if (/already registered|already been registered/i.test(mailErr.message)) {
      const { error: linkErr } = await admin.auth.admin.generateLink({ type: "magiclink", email, options: { redirectTo: link } });
      if (!linkErr) return res.status(200).json({ ok: true, emailed: true, via: "supabase-magic", link });
    }
    // 3) Couldn't email — return the link so the inviter can share it.
    return res.status(200).json({ ok: true, emailed: false, link, note: (resend.reason ? "Resend: " + resend.reason + ". " : "") + "Email couldn't be sent (" + mailErr.message + "). Share the link manually." });
  } catch (e) {
    return res.status(200).json({ ok: true, emailed: false, link, note: "Email couldn't be sent. Share the link manually." });
  }
}
